### ISSUE TITLE
RA-08H - No Region files other then CN470..

### ISSUE THREAD

**Issue by guvoltd** [Ai-Thinker-Open/Ai-Thinker-LoRaWAN-Ra-08#11]
the folder path  [https://github.com/Ai-Thinker-Open/Ai-Thinker-LoRaWAN-Ra-08/tree/main/lora/linkwan/region](url) has no other region files. update your git source

logs:

`out/lorawan_at.elf
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: out/Region.o: in function `RegionGetPhyParam':
Region.c:(.text.RegionGetPhyParam+0xa): undefined reference to `RegionEU868GetPhyParam'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: out/Region.o: in function `RegionSetBandTxDone':
Region.c:(.text.RegionSetBandTxDone+0x6): undefined reference to `RegionEU868SetBandTxDone'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: out/Region.o: in function `RegionInitDefaults':
Region.c:(.text.RegionInitDefaults+0x6): undefined reference to `RegionEU868InitDefaults'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: out/Region.o: in function `RegionVerify':
Region.c:(.text.RegionVerify+0xa): undefined reference to `RegionEU868Verify'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: out/Region.o: in function `RegionApplyCFList':
Region.c:(.text.RegionApplyCFList+0x6): undefined reference to `RegionEU868ApplyCFList'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: out/Region.o: in function `RegionChanMaskSet':
Region.c:(.text.RegionChanMaskSet+0x6): undefined reference to `RegionEU868ChanMaskSet'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: out/Region.o: in function `RegionAdrNext':
Region.c:(.text.RegionAdrNext+0x14): undefined reference to `RegionEU868AdrNext'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: out/Region.o: in function `RegionComputeRxWindowParameters':
Region.c:(.text.RegionComputeRxWindowParameters+0x14): undefined reference to `RegionEU868ComputeRxWindowParameters'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: out/Region.o: in function `RegionRxConfig':
Region.c:(.text.RegionRxConfig+0xa): undefined reference to `RegionEU868RxConfig'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: out/Region.o: in function `RegionTxConfig':
Region.c:(.text.RegionTxConfig+0x12): undefined reference to `RegionEU868TxConfig'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: out/Region.o: in function `RegionLinkAdrReq':
Region.c:(.text.RegionLinkAdrReq+0x16): undefined reference to `RegionEU868LinkAdrReq'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: out/Region.o: in function `RegionRxParamSetupReq':
Region.c:(.text.RegionRxParamSetupReq+0x6): undefined reference to `RegionEU868RxParamSetupReq'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: out/Region.o: in function `RegionNewChannelReq':
Region.c:(.text.RegionNewChannelReq+0x6): undefined reference to `RegionEU868NewChannelReq'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: out/Region.o: in function `RegionTxParamSetupReq':
Region.c:(.text.RegionTxParamSetupReq+0x6): undefined reference to `RegionEU868TxParamSetupReq'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: out/Region.o: in function `RegionDlChannelReq':
Region.c:(.text.RegionDlChannelReq+0x6): undefined reference to `RegionEU868DlChannelReq'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: out/Region.o: in function `RegionAlternateDr':
Region.c:(.text.RegionAlternateDr+0x6): undefined reference to `RegionEU868AlternateDr'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: out/Region.o: in function `RegionCalcBackOff':
Region.c:(.text.RegionCalcBackOff+0x6): undefined reference to `RegionEU868CalcBackOff'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: out/Region.o: in function `RegionNextChannel':
Region.c:(.text.RegionNextChannel+0x14): undefined reference to `RegionEU868NextChannel'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: out/Region.o: in function `RegionSetContinuousWave':
Region.c:(.text.RegionSetContinuousWave+0x6): undefined reference to `RegionEU868SetContinuousWave'
/usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: out/Region.o: in function `RegionApplyDrOffset':
Region.c:(.text.RegionApplyDrOffset+0x12): undefined reference to `RegionEU868ApplyDrOffset'
collect2: error: ld returned 1 exit status
make: *** [/mnt/d/pro_intro/abhed_old/AI-ThinkerRA08h/Ai-Thinker-LoRaWAN-Ra-08-main/Ai-Thinker-LoRaWAN-Ra-08-main/build/make/common.mk:93: out/lorawan_at.elf] Error 1`

**Comment by Rita858** [comment]
Our SDK is complete and there is no shortage of things. pls get SDK through git tool.
[Ai-Thinker-LoRaWAN-Ra-08/tree/main/lora/mac](https://github.com/Ai-Thinker-Open/Ai-Thinker-LoRaWAN-Ra-08/tree/main/lora/mac)

**Comment by guvoltd** [comment]
> Our SDK is complete and there is no shortage of things. pls get SDK through git tool. [Ai-Thinker-LoRaWAN-Ra-08/tree/main/lora/mac](https://github.com/Ai-Thinker-Open/Ai-Thinker-LoRaWAN-Ra-08/tree/main/lora/mac)

Thanks Rita, cloning repo removed errors..
